### PR TITLE
Simple update to GNOME 43 runtime

### PR DESCRIPTION
**Pull request by sukahiroaki**

### CODE REVIEW

**Comment by sukahiroaki** [comment]
Tested, works fine

**Review by hughsie — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
Please drop the meson module as well , the sdk should have a recent enough version now

**Comment by sukahiroaki** [comment]
bot, build

**Comment by sukahiroaki** [comment]
Tested, still works fine.

**Pull request merged**
