### PR TITLE
Update runtime to 3.38

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by FakeShemp** [comment]
bot, build

**Comment by Eonfge** [comment]
@FakeShemp You could try to include systemd wholesale. Here are the instructions for GNOME Logs:
https://github.com/flathub/org.gnome.Logs/blob/master/org.gnome.Logs.json

**Comment by FakeShemp** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Seems to run fine.

**Comment by hughsie** [comment]
What's the build time increase or flatpak size increase building all of systemd? It seems like something that belongs in the common modules, no?

**Comment by Eonfge** [comment]
@hughsie I certainly agree that this belongs in the Free Desktop runtime... but there is still a vocal minority that doesn't like systemd, and this is no hill to die on.

As for package size. Current release is `631.8 kB` and this merge-request comes in at `875.1 kB`, so it hardly matters.

**Comment by hughsie** [comment]
> I certainly agree that this belongs in the Free Desktop runtime

Totally agreed. Not super happy about it, but I don't have any better ideas.

**Pull request merged**
